---
title: "Functions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Shooting percentages by season
```{r}
# Corner 3 percentage for a given season:
corner3percentage <- function(season = str()){
  corner <- shootingdata %>% filter(slugSeason == season & zoneBasic != "Above the Break 3" & zoneBasic != "Backcourt" & zoneBasic != "In The Paint (Non-RA)" & zoneBasic != "Mid-Range" & zoneBasic != "Restricted Area")
cornermakes <- sum(corner$isShotMade, na.rm = TRUE)
cornerattempts <- nrow(corner)
cornerpercentage <- cornermakes / cornerattempts
return(cornerpercentage)
}

# ATB 3 percentage for a given season:
atb3percentage <- function(season = str()){
  atb <- shootingdata %>% filter(slugSeason == season & zoneBasic == "Above the Break 3") %>% group_by(typeEvent)
  atbmakes <- sum(atb$isShotMade, na.rm = TRUE)
  atbattempts <- nrow(atb)
  atbpercentage <- atbmakes / atbattempts
  return(atbpercentage)
}

# Restricted area percentage for a given season:
restrictedpercentage <- function(season = str()){
 restricted <- shootingdata %>% filter(slugSeason == season & zoneBasic == "Restricted Area") %>% group_by(typeEvent)
 restrictedmakes <- sum(restricted$isShotMade, na.rm = TRUE)
 restrictedattempts <- nrow(restricted)
 restrictedpercentage <- restrictedmakes / restrictedattempts
 return(restrictedpercentage)
}

# Floater-Range percentage for a given season:
floaterpercentage <- function(season = str()){
  floater <- shootingdata %>% filter(slugSeason == season & zoneBasic == "In The Paint (Non-RA)") %>% group_by(typeEvent)
  floatermakes <- sum(floater$isShotMade, na.rm = TRUE)
  floaterattempts <- nrow(floater)
  floaterp <- floatermakes / floaterattempts
  return(floaterp)
}

# Mid-Range percentage for a given season:
midrangepercentage <- function(season = str()){
    midrange <- shootingdata %>% filter(slugSeason == season & zoneBasic == "Mid-Range") %>% group_by(typeEvent)
    midrangemakes <- sum(midrange$isShotMade, na.rm = TRUE)
    midrangeattempts <- nrow(midrange)
    midrangep <- midrangemakes / midrangeattempts
    return(midrangep)
  }
  
# Chances (shots + passes made a player makes in a given season)
chances <- function(season = str(), id = int()){
  passes <- Passing %>% filter(SEASON == season & idPlayer == id) %>% summarise(PASSES_MADE)
  shots <- shootingdata %>% filter(slugSeason == season & idPlayer == id) %>% summarise(n())
  totalchances = as.integer(passes) + as.integer(shots)
  return(totalchances)
}

```

# Returns player id given name:
```{r}
nametoid <- function(name){
  rosters <- read.csv("/Users/patricksimpson/Desktop/NBAHC/rosters.csv")
  rosters <- rosters %>% filter(namePlayer == name)
  id <- rosters[1,14]
  return(id)
}
```

# Getting Games Played in a Season:
```{r}
gamesplayed <- function(id, season){
  df <- read.csv("/Users/patricksimpson/Desktop/NBAHC/Playmaking/Passing.csv")
  df <- df %>% filter(idPlayer == id) %>% filter(SEASON == season)
  value <- ifelse(is.na(as.integer(df[1,5])), 0, as.integer(df[1,5]))
  return(value)
}
```

# Getting Minutes Played in a Season:
```{r}
minutesplayed <- function(id, season){
  df <- read.csv("/Users/patricksimpson/Desktop/NBAHC/Playmaking/Passing.csv")
  df <- df %>% filter(idPlayer == id) %>% filter(SEASON == season)
  value <- ifelse(is.na(as.integer(df[1,8])), 0, as.integer(df[1,8]))
  return(value)
}
```

# Function that returns three point shooting data for a player in a given season:
```{r}
dribdefense <- read.csv("/Users/patricksimpson/Desktop/NBAHC/dribdefense.csv")
shootingdata <- read.csv("/Users/patricksimpson/Desktop/NBAHC/Shooting/shootingdata.csv")

threepointshooting <- function(id, season){
  dribdefense <- dribdefense %>% filter(idPlayer == id & Season == season)
  tight <- dribdefense %>% filter(CloseDefDistRange != "4-6 Feet - Open" & CloseDefDistRange != "6+ Feet - Wide Open")
  open <- dribdefense %>% filter(CloseDefDistRange != "0-2 Feet - Very Tight" & CloseDefDistRange != "2-4 Feet - Tight" & CloseDefDistRange != "6+ Feet - Wide Open")
  wideopen <- dribdefense %>% filter(CloseDefDistRange != "0-2 Feet - Open" & CloseDefDistRange != "2-4 Feet - Tight" & CloseDefDistRange != "4-6 Feet - Open")
  
  tightattempts <- sum(tight$fg3a) # Tight Attempts
  tightmakes <- sum(tight$fg3m) # Tight Makes
  openattempts <- sum(open$fg3a) # Open Attempts
  openmakes <- sum(open$fg3m) # Open Makes
  wideopenattempts <- sum(wideopen$fg3a) # Wide Open Attempts
  wideopenmakes <- sum(wideopen$fg3m) # Wide Open Makes
  
  tightprop <- tightattempts / (tightattempts + openattempts + wideopenattempts) # Tight Proportion
  openprop <- openattempts / (tightattempts + openattempts + wideopenattempts) # Open Proportion
  wideopenprop <- wideopenattempts / (tightattempts + openattempts + wideopenattempts) # Wide Open Proportion
  
  tightpercentage <- tightmakes / tightattempts # Tight Percentage
  openpercentage <- openmakes / openattempts # Open Percentage
  wideopenpercentage <- wideopenmakes / wideopenattempts # Wide Open Percentage
  
  shootingdata <- shootingdata %>% filter(slugSeason == season & idPlayer == id & typeShot == "3PT Field Goal")
  atb <- shootingdata %>% filter(zoneBasic == "Above the Break 3")
  corner <- shootingdata %>% filter(zoneBasic != "Above the Break 3" & zoneBasic != "In The Paint (Non-RA)" & zoneBasic != "Mid-Range" & zoneBasic != "Restricted Area" & zoneBasic != "Backcourt")
  
  threeattempts <- nrow(shootingdata) # Total 3PT Attempts
  
  atbattempts <- nrow(atb) # ATB Attempts
  atbmakes <- sum(atb$typeEvent == "Made Shot") # ATB makes
  cornerattempts <- nrow(corner) # Corner Attempts
  cornermakes <- sum(corner$typeEvent == "Made Shot") # Corner Makes
  
  atbprop <- atbattempts / (atbattempts + cornerattempts) # ATB Proportion
  cornerprop <- cornerattempts / (atbattempts + cornerattempts) # Corner Proportion
  
  atbpercentage <- atbmakes / atbattempts # ATB Percentage
  cornerpercentage <- cornermakes / cornerattempts # Corner Percentage
  
  name <- idtoname(id) # Player name
  gp <- gamesplayed(id, season) # Games Played
  mp <- minutesplayed(id, season) # Minutes Played
  pos <- position(id, season) # Position Played
  fg3ag <- threeattempts / gp # 3 point attempts per game
  
  playerdf <- as.data.frame(cbind(name, id, season, pos, gp, mp, threeattempts, fg3ag, tightprop, openprop, wideopenprop, tightpercentage, openpercentage, wideopenpercentage, atbprop, cornerprop, atbpercentage, cornerpercentage))
  
  colnames(playerdf) <- c("namePlayer", "idPlayer", "Season", "position", "gamesPlayed", "minutesPlayed", "FG3A", "FG3AG", "tightProp", "openProp", "wideopenProp", "tight%", "open%", "wideopen%",
                      "atbProp", "cornerProp", "atb%", "corner%")
  return(playerdf)                    
}
```

# Three point percentages based on defender proximity in a given season:
```{r}
openpercentage <- function(season){
  df <- dribdefense %>% filter(CloseDefDistRange != "0-2 Feet - Very Tight" & CloseDefDistRange != "2-4 Feet - Tight" & CloseDefDistRange != "6+ Feet - Wide Open" & Season == season)
  attempts <- sum(df$fg3a)
  makes <- sum(df$fg3m)
  percentage <- makes / attempts
  return(percentage)
}

wideopenpercentage <- function(season){
  df <- dribdefense %>% filter(CloseDefDistRange != "0-2 Feet - Very Tight" & CloseDefDistRange != "2-4 Feet - Tight" & CloseDefDistRange != "4-6 Feet - Open" & Season == season)
  attempts <- sum(df$fg3a)
  makes <- sum(df$fg3m)
  percentage <- makes / attempts
  return(percentage)
}

tightpercentage <- function(season){
  df <- dribdefense %>% filter(CloseDefDistRange != "6+ Feet - Wide Open" & CloseDefDistRange != "4-6 Feet - Open" & Season == season)
  attempts <- sum(df$fg3a)
  makes <- sum(df$fg3m)
  percentage <- makes / attempts
  return(percentage)
}
```

```{r}
synergyoffense$Season <- as.character(synergyoffense$Season)
synergyoffense$groupPos <- as.character(synergyoffense$groupPos)

# Avg. roll PPP based on position:
rollppp <- function(Position, season){
  roll <- as.numeric(synergyoffense %>% filter(groupPos == Position & PlayType == "PRRollMan" & Season == season & poss >= 50) %>% summarise(mean(ppp)))
  return(roll)
}

# Avg. trans PPP based on postion:
transppp <- function(Position, season){
  trans <- as.numeric(synergyoffense %>% filter(groupPos == Position & PlayType == "Transition" & Season == season & poss >= 50) %>% summarise(mean(ppp)))
  return(trans)
}

restrictedpercentage <- function(postion, season){
    restricted <- shootingdata %>% filter(slugSeason == season & zoneBasic == "Restricted Area") %>% group_by(typeEvent)
    restrictedmakes <- sum(restricted$isShotMade, na.rm = TRUE)
    restrictedattempts <- nrow(restricted)
    restrictedpercentage <- restrictedmakes / restrictedattempts
    return(restrictedpercentage)
}
```

# Function that returns Finishing dataframe for single player:
```{r}
finishing <- function(id, season){
  # Starting with synergy data:
  syn <- synergyoffense %>% filter(Season == season & idPlayer == id)
  # Roll
  roll <- syn %>% filter(PlayType == "PRRollMan")
  rollposs <- as.integer(roll[1,13])
  rollfreq <- as.numeric(roll[1,14])
  rollppp <- as.numeric(roll[1,18])
  # Cut
  cut <- syn %>% filter(PlayType == "Cut")
  cutposs <- as.integer(cut[1,13])
  cutfreq <- as.numeric(cut[1,14])
  cutppp <- as.numeric(cut[1,18])
  # OffRebound
  reb <- syn %>% filter(PlayType == "OffRebound")
  rebposs <- as.integer(reb[1,13])
  rebfreq <- as.numeric(reb[1,14])
  rebppp <- as.numeric(reb[1,18])
  # Transition
  trans <- syn %>% filter(PlayType == "Transition")
  transposs <- as.integer(trans[1,13])
  transfreq <- as.numeric(trans[1,14])
  transppp <- as.numeric(trans[1,18])
  
  # Looking at ShootingData DF:
  shot <- shootingdata %>% filter(slugSeason == season & idPlayer == id)
  fga <- nrow(shot) # Number of shots attempted during year
  restrictatt <- as.integer(shot %>% filter(zoneBasic == "Restricted Area") %>% summarise(n=n())) # RA attempts
  restrictmakes <- as.integer(shot %>% filter(zoneBasic == "Restricted Area") %>% summarise(n=sum(typeEvent=="Made Shot")))
  paintatt <- as.integer(shot %>% filter(zoneBasic == "In The Paint (Non-RA)") %>% summarise(n=n())) # Paint attempts
  paintmakes <- as.integer(shot %>% filter(zoneBasic == "In The Paint (Non-RA)") %>% summarise(n=sum(typeEvent=="Made Shot")))
  
  restrictprop <- restrictatt / fga
  restrictfgp <- restrictmakes / restrictatt
  paintprop <- paintatt / fga
  paintfgp <- paintmakes / paintatt
  
  name <- idtoname(id)
  
  df <- as.data.frame(cbind(name, id, season, rollposs, rollfreq, rollppp, cutposs, cutfreq, cutppp, rebposs, rebfreq, rebppp, transposs, transfreq, transppp, restrictprop, restrictfgp, paintprop, paintfgp))
  row.names(df) <- c()
  colnames(df) <- c("namePlayer", "idPlayer", "Season", "rollPoss", "rollFreq", "rollPPP", "cutPoss", "cutFreq", "cutPPP", "rebPoss", "rebFreq", "rebPPP", "transPoss", "transFreq", "transPPP", "restrictProp", "restrictFGP", "paintProp", "paintFGP")
  return(df)
}
```
