---
title: "Finishing Component"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
season <- "2018-19"
# Getting rosters for given season
players <- rosters %>% filter(slugSeason == season)
players$namePlayer <- as.character(players$namePlayer)
players$idPlayer <- as.integer(players$idPlayer)
seasonshots <- shootingdata %>% filter(slugSeason == season)
mysynergy <- synergydata %>% filter(Season == season)

for(i in 1:nrow(players)){
  playername <- players[i,5] # Player Name
  playerid <- players[i,14] # Player ID
  
  # Restricted Area FGA
  rafga <- as.integer(seasonshots %>% filter(idPlayer == as.integer(playerid)) %>% filter(zoneBasic == "Restricted Area") %>% summarise(fga = n()))
  # Restricted Area FGM
  rafgm <- as.integer(seasonshots %>% filter(idPlayer == as.integer(playerid)) %>% filter(zoneBasic == "Restricted Area") %>% summarise(fga = sum(isShotMade)))

  # Paint FGA
  pfga <- as.integer(seasonshots %>% filter(idPlayer == as.integer(playerid)) %>% filter(zoneBasic == "In The Paint (Non-RA)") %>% summarise(fga = n()))
  # Paint FGM
  pfgm <- as.integer(seasonshots %>% filter(idPlayer == as.integer(playerid)) %>% filter(zoneBasic == "In The Paint (Non-RA)") %>% summarise(fga = sum(isShotMade)))

  # Possessions as the roll man
  rollposs <- as.integer(mysynergy %>% filter(idPlayer == as.integer(playerid)) %>% filter(PlayType == "PRRollMan") %>% summarise(poss = sum(poss)))
  
  # PPP as the roll man
  rollppp <- as.numeric(mysynergy %>% filter(idPlayer == as.integer(playerid)) %>% filter(PlayType == "PRRollMan") %>%
                          summarise(ppp = sum(ppp)))
  
  # Possessions in transition
  transposs <- as.integer(mysynergy %>% filter(idPlayer == as.integer(playerid)) %>% filter(PlayType == "Transition") %>% summarise(poss = sum(poss)))

  # PPP in transition
  transppp <- as.numeric(mysynergy %>% filter(idPlayer == as.integer(playerid)) %>% filter(PlayType == "Transition") %>%
                          summarise(ppp = sum(ppp)))

  playerdf <- as.data.frame(cbind(season, playername, playerid, rafga, rafgm, pfga, pfgm, rollposs, rollppp, transposs, transppp))
  
  remove(rafga, rafgm, pfga, pfgm, rollposs, rollppp, transposs, transppp)
  
  if(i == 1){
    finishing <- playerdf
  } else{
    helper <- playerdf
    finishing <- rbind(finishing, helper)
  }
  
}

remove(helper, playerdf)

finishing$season <- as.character(finishing$season)
finishing$playername <- as.character(finishing$playername)
finishing$playerid <- as.integer(as.character(finishing$playerid))
finishing$rafga <- as.integer(as.character(finishing$rafga))
finishing$rafgm <- as.integer(as.character(finishing$rafgm))
finishing$pfga <- as.integer(as.character(finishing$pfga))
finishing$pfgm <- as.integer(as.character(finishing$pfgm))
finishing$rollposs <- as.integer(as.character(finishing$rollposs))
finishing$rollppp <- as.numeric(as.character(finishing$rollppp))
finishing$transposs <- as.integer(as.character(finishing$transposs))
finishing$transppp <- as.numeric(as.character(finishing$transppp))




```
