---
title: "ShootingComponent"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(nbastatR)
```

# Getting shooting component of matrix for 2018-19 Season
```{r}
season <- "2018-19"
# Getting rosters for given season
players <- rosters %>% filter(slugSeason == season)
players$namePlayer <- as.character(players$namePlayer)
seasonshots <- shootingdata %>% filter(slugSeason == season)

for (i in 1:nrow(players)) {
  playerid <- players[i, 14] # ID of player being searched
  playername <- players[i, 5] # Name of player being searched
  # Obtaining 3PA:
  defensedf <- dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season)
  gamesplayed <- defensedf[1,14]
  threePA <- as.integer(sum(defensedf$fg3a)) # Number of 3pa
  verytight <- defensedf %>% filter(CloseDefDistRange == "0-2 Feet - Very Tight") %>% summarise(tpa = sum(fg3a))
  tight <- defensedf %>% filter(CloseDefDistRange == "2-4 Feet - Tight") %>% summarise(tpa = sum(fg3a))
  open <- defensedf %>% filter(CloseDefDistRange == "4-6 Feet - Open") %>% summarise(tpa = sum(fg3a))
  wideopen <- defensedf %>% filter(CloseDefDistRange == "6+ Feet - Wide Open") %>% summarise(tpa = sum(fg3a))
  tight3pa <- as.integer(verytight) + as.integer(tight) # Tight 3 point attempts
  open3pa <- as.integer(open) # Open 3 Point attempts
  wideopen3pa <- as.integer(wideopen) # Wide open 3 point attempts
  remove(verytight, tight, open, wideopen)
  # Now getting data on makes vs. misses
  verytight <- defensedf %>% filter(CloseDefDistRange == "0-2 Feet - Very Tight") %>% summarise(tpa = sum(fg3m))
  tight <- defensedf %>% filter(CloseDefDistRange == "2-4 Feet - Tight") %>% summarise(tpa = sum(fg3m))
  open <- defensedf %>% filter(CloseDefDistRange == "4-6 Feet - Open") %>% summarise(tpa = sum(fg3m))
  wideopen <- defensedf %>% filter(CloseDefDistRange == "6+ Feet - Wide Open") %>% summarise(tpa = sum(fg3m))
  tight3fgm <- as.integer(verytight) + as.integer(tight) # tight 3 point makes
  open3fgm <- as.integer(open) # open 3 point makes
  wideopen3fgm <- as.integer(wideopen) # wide open 3 point makes
  remove(verytight, tight, open, wideopen)

  # Obtaining % assisted vs. unassisted:
  catch <- defensedf %>% filter(rangeDribble == "0 Dribbles") %>% summarise(n = sum(fg3a))
  onedrib <- defensedf %>% filter(rangeDribble == "1 Dribble") %>% summarise(n = sum(fg3a))
  twodrib <- defensedf %>% filter(rangeDribble == "2 Dribbles") %>% summarise(n = sum(fg3a))
  threedrib <- defensedf %>% filter(rangeDribble == "3-6 Dribbles") %>% summarise(n = sum(fg3a))
  sevenplus <- defensedf %>% filter(rangeDribble == "7+ Dribbles") %>% summarise(n = sum(fg3a))
  assisted <- as.integer(catch) + as.integer(onedrib) # Shots attempts off potential assist
  unassisted <- as.integer(twodrib) + as.integer(threedrib) + as.integer(sevenplus) # Shot created by player
  remove(catch, onedrib, twodrib, threedrib, sevenplus)
  catch <- defensedf %>% filter(rangeDribble == "0 Dribbles") %>% summarise(n = sum(fg3m))
  onedrib <- defensedf %>% filter(rangeDribble == "1 Dribble") %>% summarise(n = sum(fg3m))
  twodrib <- defensedf %>% filter(rangeDribble == "2 Dribbles") %>% summarise(n = sum(fg3m))
  threedrib <- defensedf %>% filter(rangeDribble == "3-6 Dribbles") %>% summarise(n = sum(fg3m))
  sevenplus <- defensedf %>% filter(rangeDribble == "7+ Dribbles") %>% summarise(n = sum(fg3m))
  assisstedmakes <- as.integer(catch) + as.integer(onedrib) # assisted makes
  unassistedmakes <- as.integer(twodrib) + as.integer(threedrib) + as.integer(sevenplus) # unassisted makes
  remove(catch, onedrib, twodrib, threedrib, sevenplus)

  # Obtaining percent ATB vs. Corner
  playershots <- seasonshots %>% filter(typeShot == "3PT Field Goal") %>% filter(idPlayer == as.integer(playerid)) # all 3 point shots attempted
  atb <- as.integer(playershots %>% filter(zoneBasic == "Above the Break 3") %>% summarise(x = n()))
  leftcorner <- as.integer(playershots %>% filter(zoneBasic == "Left Corner 3") %>% summarise(x = n()))
  rightcorner <- as.integer(playershots %>% filter(zoneBasic == "Right Corner 3") %>% summarise(x = n()))
  corner <- leftcorner + rightcorner
  remove(leftcorner, rightcorner)
  # Getting makes from each location
  atbmakes <- as.integer(playershots %>% filter(zoneBasic == "Above the Break 3") %>% summarise(x = sum(isShotMade)))
  lcmakes <- as.integer(playershots %>% filter(zoneBasic == "Left Corner 3") %>% summarise(x = sum(isShotMade)))
  rcmakes <- as.integer(playershots %>% filter(zoneBasic == "Right Corner 3") %>% summarise(x = sum(isShotMade)))
  cornermakes <- lcmakes + rcmakes
  remove(lcmakes, rcmakes)
  
  # Putting together dataframe for player:
  playerdf <- as.data.frame(cbind(playername, playerid, gamesplayed, threePA, tight3pa, open3pa, wideopen3pa, tight3fgm, open3fgm, wideopen3fgm, assisted, unassisted, assisstedmakes, unassistedmakes, atb, corner, atbmakes, cornermakes))
  
  remove(playername, playerid, gamesplayed, threePA, tight3pa, open3pa, wideopen3pa, tight3fgm, open3fgm, wideopen3fgm, assisted, unassisted, assisstedmakes, unassistedmakes, atb, corner, atbmakes, cornermakes)
  
  # Putting large df together:
  if (i == 1) {
    shootingcomponent <- playerdf
  } else{
    helper <- playerdf
    shootingcomponent <- rbind(shootingcomponent, helper)
  }
  
  i = i + 1
  
}
remove(playerdf, helper)
playercolumn <- players$namePlayer
shootingcomponent$playername <- playercolumn

# Turning numbers into proportions
# shootingcomponent <- shootingcomponent %>% mutate(tight3pa = tight3pa / threePA) %>% mutate(open3pa = open3pa / threePA) %>% mutate(wideopen3pa = wideopen3pa / threePA) %>% mutate(assisted = assisted / threePA) %>% mutate(unassisted = unassisted / threePA) %>% mutate(atb = atb / threePA) %>% mutate(corner = corner / threePA)

# Obtaining league averages...
defense <- dribdefense %>% filter(Season == season) %>% group_by(CloseDefDistRange) %>% summarise(tpa = sum(fg3a), tpm = sum(fg3m)) %>% mutate(percentage = tpm / tpa) # Percentages based on defender distance
newrow <- as.data.frame(cbind(defense[1,2]+defense[2,2], defense[1,3]+defense[2,3]))
newrow <- newrow %>% mutate(percentage = tpm / tpa)
newrow <- as.data.frame(cbind("Tight", newrow))
colnames(newrow) <- c("CloseDefDistRange", "tpm", "tpa", "percentage")
defense <- rbind(newrow, defense)
remove(newrow)
defense <- defense[-c(2,3),]
shottypes <- c("Tight", "Open", "Wide Open")
defense$CloseDefDistRange <- shottypes
remove(shottypes)
tightpercentage <- defense[1,4] # League average tight 3s
openpercentage <- defense[2,4] # League average open 3s
wideopenpercentage <- defense[3,4] # League average wide open 3s
remove(defense)

dribbles <- dribdefense %>% filter(Season == season) %>% group_by(rangeDribble) %>% summarise(tpa = sum(fg3a), tpm = sum(fg3m)) %>% mutate(percentage = tpm / tpa) # percentages based on dribbles taken
newrow1 <- as.data.frame(cbind(dribbles[1,2]+dribbles[2,2],dribbles[1,3]+dribbles[2,3]))
newrow1 <- newrow1 %>% mutate(percentage = tpm/tpa)
newrow1 <- as.data.frame(cbind("assisted", newrow1))
newrow2 <- as.data.frame(cbind(dribbles[3,2]+dribbles[4,2]+dribbles[5,2],dribbles[3,3]+dribbles[4,3]+dribbles[5,3]))
newrow2 <- newrow2 %>% mutate(percentage = tpm/tpa)
newrow2 <- as.data.frame(cbind("unassisted", newrow2))
remove(dribbles)
colnames(newrow1) <- c("ShotType", "tpa", "tpm", "percentage")
colnames(newrow2) <- c("ShotType", "tpa", "tpm", "percentage")
dribbles <- rbind(newrow1, newrow2)
remove(newrow1, newrow2)
assistedpercentage <- dribbles[1,4] # Percentage on assisted shots
unassistedpercentage <- dribbles[2,4] # Percentage on unassisted shots
remove(dribbles)

location <- seasonshots %>% filter(typeShot == "3PT Field Goal") %>% group_by(zoneBasic) %>% summarise(tpa = n(), tpm = sum(isShotMade)) %>% mutate(percentage = tpm / tpa) # percentages based on location
location <- location[-c(2, 4),]
newrow <- as.data.frame(cbind(location[2,2]+location[3,2], location[2,3]+location[3,3]))
newrow <- newrow %>% mutate(percentage = tpm / tpa)
newrow <- as.data.frame(cbind("Corner", newrow))
colnames(newrow) <- c("zoneBasic", "tpa", "tpm", "percentage")
location <- rbind(location, newrow)
remove(newrow)
location <- location[-c(2,3),]
atbpercentage <- as.numeric(location[1,4]) # ATB 3 percentage
cornerpercentage <- as.numeric(location[2,4]) # Corner 3 percentage
remove(location)

# Removing all NA values
shootingcomponent[is.na(shootingcomponent)] <- 0

# Changing columns from factors to integers
shootingcomponent$playerid <- as.integer(as.character(shootingcomponent$playerid))
shootingcomponent$gamesplayed <- as.integer(as.character(shootingcomponent$gamesplayed))
shootingcomponent$threePA <- as.integer(as.character(shootingcomponent$threePA))
shootingcomponent$tight3pa <- as.integer(as.character(shootingcomponent$tight3pa))
shootingcomponent$open3pa <- as.integer(as.character(shootingcomponent$open3pa))
shootingcomponent$wideopen3pa <- as.integer(as.character(shootingcomponent$wideopen3pa))
shootingcomponent$tight3fgm <- as.integer(as.character(shootingcomponent$tight3fgm))
shootingcomponent$open3fgm <- as.integer(as.character(shootingcomponent$open3fgm))
shootingcomponent$wideopen3fgm <- as.integer(as.character(shootingcomponent$wideopen3fgm))
shootingcomponent$assisted <- as.integer(as.character(shootingcomponent$assisted))
shootingcomponent$unassisted <- as.integer(as.character(shootingcomponent$unassisted))
shootingcomponent$assisstedmakes <- as.integer(as.character(shootingcomponent$assisstedmakes))
shootingcomponent$unassistedmakes <- as.integer(as.character(shootingcomponent$unassistedmakes))
shootingcomponent$atb <- as.integer(as.character(shootingcomponent$atb))
shootingcomponent$corner <- as.integer(as.character(shootingcomponent$corner))
shootingcomponent$atbmakes <- as.integer(as.character(shootingcomponent$atbmakes))
shootingcomponent$cornermakes <- as.integer(as.character(shootingcomponent$cornermakes))
 

shootingcomponent <- shootingcomponent %>% mutate(fga3pg = threePA / gamesplayed) %>% select(playername:threePA, fga3pg, tight3pa:cornermakes)
                                      
shootingcomponent <- shootingcomponent %>% mutate(tight3fgm = ifelse(threePA >= 10 & gamesplayed >= 10, tight3fgm / tight3pa, 0)) %>% 
 mutate(open3fgm = ifelse(threePA >= 10 & gamesplayed >= 10, open3fgm / open3pa, 0)) %>% 
 mutate(wideopen3fgm = ifelse(threePA >= 10 & gamesplayed >= 10, wideopen3fgm / wideopen3pa, 0)) %>%
  mutate(tight3pa = ifelse(threePA >= 10 & gamesplayed >= 10, tight3pa / threePA, 0)) %>%
  mutate(open3pa = ifelse(threePA >= 10 & gamesplayed >= 10, open3pa / threePA, 0)) %>%
  mutate(wideopen3pa = ifelse(threePA >= 10 & gamesplayed >= 10, wideopen3pa / threePA, 0)) %>%
  mutate(assisstedmakes = ifelse(threePA >= 10 & gamesplayed >= 10, assisstedmakes / assisted, 0)) %>%
  mutate(unassistedmakes = ifelse(threePA >= 10 & gamesplayed >= 10, unassistedmakes / unassisted, 0)) %>%
  mutate(assisted = ifelse(threePA >= 10 & gamesplayed >= 10, assisted / threePA, 0)) %>%
  mutate(unassisted = ifelse(threePA >= 10 & gamesplayed >= 10, unassisted / threePA, 0)) %>%
  mutate(atbmakes = ifelse(threePA >= 10 & gamesplayed >= 10, atbmakes / atb, 0)) %>%
  mutate(cornermakes = ifelse(threePA >= 10 & gamesplayed >= 10, cornermakes / corner, 0)) %>%
  mutate(atb = ifelse(threePA >= 10 & gamesplayed >= 10, atb / threePA, 0)) %>%
  mutate(corner = ifelse(threePA >= 10 & gamesplayed >= 10, corner / threePA, 0))


shootingcomponent[is.na(shootingcomponent)] <- 0

```
