---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Obtaining location of 3 point shots attempted for each player in a given year
```{r}
# Setting year:
year = "2018-19"

# Rosters from 2018-19 season:
league <- rosters %>% filter(slugSeason == year)

# Shooting data from 2018-19 season:
shots <- shootingdata %>% filter(slugSeason == year)


for (i in 1:nrow(league)) {
  id <- league[i, 14] # Player id
  nameplayer <- allplayers %>% filter(idPlayer == as.integer(id)) # Player name
  nameplayer <- nameplayer[1, 3]
  mydf <- shots %>% filter(typeShot == "3PT Field Goal") %>% filter(idPlayer == as.integer(id))
  mydf <- subset(mydf, zoneBasic != "Mid-Range" & zoneBasic != "Backcourt")
  mydf <- mydf %>% group_by(zoneBasic) %>% summarise(attempts = n()) %>% mutate(freq = attempts / sum(attempts))
  playerdf <- cbind(mydf[1,2], mydf[1,3], mydf[2,2], mydf[2,3], mydf[3,2], mydf[3,3])
  colnames(playerdf) <- c("a", "b", "c", "d", "e", "f")
  playerdf <- playerdf %>% mutate(g = c + e)
  playerdf <- playerdf %>% mutate(h = d + f)
  playerdf$c = NULL
  playerdf$d = NULL
  playerdf$e = NULL
  playerdf$f = NULL
  rownames(playerdf) = c(as.character(nameplayer))
 
  if(i == 1){
    master <- playerdf
  } else{
    helper <- playerdf
    master <- rbind(master, helper)
  }
  
  i = i + 1
}

  colnames(master) <- c("ATB", "ATB_Freq", "Corner", "Corner_Freq")
  remove(id, nameplayer, mydf, playerdf, helper)
```



# Obtaining how contentested the 3 point shots are for each player in a given year
```{r}

year = "2018-19"

# Rosters from season:
league <- rosters %>% filter(slugSeason == year)

# Shooting contest data from season:
contest <- shootingdefense %>% filter(SEASON == year)

for (i in 1:nrow(league)){
  id <- league[i, 14] # Player id
  nameplayer <- allplayers %>% filter(idPlayer == as.integer(id)) # Player name
  nameplayer <- nameplayer[1, 3]
  testing <- contest %>% filter(idPlayer == as.integer(id))
  playerdf <- as.data.frame(cbind(testing[1,20], testing[1,18], testing[2,20], testing[2,18], testing[3,20], testing[3,18],
                    testing[4,20], testing[4,18]))
  colnames(playerdf) <- c("a", "b", "c", "d", "e", "f", "g", "h")
  playerdf <- playerdf %>% mutate(i = b / (b+d+f+h)) %>% mutate(j = d / (b+d+f+h)) %>% 
    mutate(k = f / (b+d+f+h)) %>% mutate(l = h / (b+d+f+h))
  playerdf$b = NULL
  playerdf$d = NULL
  playerdf$f = NULL
  playerdf$h = NULL
  playerdf <- playerdf %>% select(a, i, c, j, e, k, g, l)

  rownames(playerdf) <- c(as.character(nameplayer))
  
  if(i == 1){
    shot <- playerdf
  } else{
    helper <- playerdf
    shot <- rbind(shot, helper)
  }
  
  i = i + 1
  
}

remove(id, nameplayer, testing, playerdf, helper)
colnames(shot) <- c("0-2", "0-2 Freq", "2-4", "2-4 Freq", "4-6", "4-6 Freq", "6+", "6+ Freq")
view(shot)



x <- teams_players_stats(seasons = 2019, types = c("player"), tables = c("shots"), modes = c("Totals"), dribble_ranges = c("0 Dribbles", "1 Dribble", "2 Dribbles", "3-6 Dribbles", "7%2B Dribbles"))
x1 <- x[[7]][[1]]
x2 <- x[[7]][[2]]
x3 <- x[[7]][[3]]
x4 <- x[[7]][[4]]
x5 <- x[[7]][[5]]
x <- rbind(x1, x2, x3, x4, x5)
x <- mutate(x, Season = "2018-19")
remove(x1, x2, x3, x4, x5)
x <- x %>% select(Season, idPlayoffRound:frequencyFG3A)

y <- teams_players_stats(seasons = 2018, types = c("player"), tables = c("shots"), modes = c("Totals"), dribble_ranges = c("0 Dribbles", "1 Dribble", "2 Dribbles", "3-6 Dribbles", "7%2B Dribbles"))
y1 <- y[[7]][[1]]
y2 <- y[[7]][[2]]
y3 <- y[[7]][[3]]
y4 <- y[[7]][[4]]
y5 <- y[[7]][[5]]
y <- rbind(y1, y2, y3, y4, y5)
y <- mutate(y, Season = "2017-18")
remove(y1, y2, y3, y4, y5)
y <- y %>% select(Season, idPlayoffRound:frequencyFG3A)


z <- teams_players_stats(seasons = 2017, types = c("player"), tables = c("shots"), modes = c("Totals"), dribble_ranges = c("0 Dribbles", "1 Dribble", "2 Dribbles", "3-6 Dribbles", "7%2B Dribbles"))
z1 <- z[[7]][[1]]
z2 <- z[[7]][[2]]
z3 <- z[[7]][[3]]
z4 <- z[[7]][[4]]
z5 <- z[[7]][[5]]
z <- rbind(z1, z2, z3, z4, z5)
z <- mutate(z, Season = "2016-17")
remove(z1, z2, z3, z4, z5)
z <- z %>% select(Season, idPlayoffRound:frequencyFG3A)




k <- teams_players_stats(seasons = 2016, types = c("player"), tables = c("shots"), modes = c("Totals"), dribble_ranges = c("0 Dribbles", "1 Dribble", "2 Dribbles", "3-6 Dribbles", "7%2B Dribbles"))
k1 <- k[[7]][[1]]
k2 <- k[[7]][[2]]
k3 <- k[[7]][[3]]
k4 <- k[[7]][[4]]
k5 <- k[[7]][[5]]
k <- rbind(k1, k2, k3, k4, k5)
k <- mutate(k, Season = "2015-16")
remove(k1, k2, k3, k4, k5)
k <- k %>% select(Season, idPlayoffRound:frequencyFG3A)


l <- teams_players_stats(seasons = 2015, types = c("player"), tables = c("shots"), modes = c("Totals"), dribble_ranges = c("0 Dribbles", "1 Dribble", "2 Dribbles", "3-6 Dribbles", "7%2B Dribbles"))
l1 <- l[[7]][[1]]
l2 <- l[[7]][[2]]
l3 <- l[[7]][[3]]
l4 <- l[[7]][[4]]
l5 <- l[[7]][[5]]
l <- rbind(l1, l2, l3, l4, l5)
l <- mutate(l, Season = "2014-15")
remove(l1, l2, l3, l4, l5)
l <- l %>% select(Season, idPlayoffRound:frequencyFG3A)

p <- teams_players_stats(seasons = 2014, types = c("player"), tables = c("shots"), modes = c("Totals"), dribble_ranges = c("0 Dribbles", "1 Dribble", "2 Dribbles", "3-6 Dribbles", "7%2B Dribbles"))
p1 <- p[[7]][[1]]
p2 <- p[[7]][[2]]
p3 <- p[[7]][[3]]
p4 <- p[[7]][[4]]
p5 <- p[[7]][[5]]
p <- rbind(p1, p2, p3, p4, p5)
p <- mutate(p, Season = "2013-14")
remove(p1, p2, p3, p4, p5)
p <- p %>% select(Season, idPlayoffRound:frequencyFG3A)




dribbling <- rbind(x, y, z, k, l, p)



#https://stats.nba.com/players/shots-dribbles/?Season=2018-19&SeasonType=Regular%20Season&PerMode=Totals&sort=PLAYER_NAME&dir=-1




#https://stats.nba.com/stats/leaguedashplayerptshot?CloseDefDistRange=&College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&DribbleRange=7%2B+Dribbles&GameScope=&GameSegment=&GeneralRange=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2018-19&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&ShotDistRange=&StarterBench=&TeamID=0&TouchTimeRange=&VsConference=&VsDivision=&Weight=


#https://stats.nba.com/stats/leaguedashplayerptshot?CloseDefDistRange=&College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&DribbleRange=3-6+Dribbles&GameScope=&GameSegment=&GeneralRange=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2018-19&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&ShotDistRange=&StarterBench=&TeamID=0&TouchTimeRange=&VsConference=&VsDivision=&Weight=

#https://stats.nba.com/stats/leaguedashplayerptshot?CloseDefDistRange=0-2+Feet+-+Very+Tight&College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&DribbleRange=&GameScope=&GameSegment=&GeneralRange=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2019-20&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&ShotDistRange=&StarterBench=&TeamID=0&TouchTimeRange=&VsConference=&VsDivision=&Weight=


#https://stats.nba.com/stats/leaguedashplayerptshot?CloseDefDistRange=6%2B+Feet+-+Wide+Open&College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&DribbleRange=&GameScope=&GameSegment=&GeneralRange=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2019-20&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&ShotDistRange=&StarterBench=&TeamID=0&TouchTimeRange=&VsConference=&VsDivision=&Weight=

```
