---
title: "Playmaking component"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
season <- "2018-19"
# Getting rosters for given season
players <- rosters %>% filter(slugSeason == season)
players$namePlayer <- as.character(players$namePlayer)
players$idPlayer <- as.integer(players$idPlayer)

for(i in 1:nrow(players)){
  playername <- players[i,5] # Player Name
  playerid <- players[i,14] # Player ID
  PAPM <- passing %>% filter(SEASON == season & idPlayer == as.integer(playerid)) %>% mutate(papm = ifelse(GP >= 10, POTENTIAL_AST/MIN, 0)) # Getting the potential assists per minute for player...
  PAPM <- PAPM[1,18]
  mydf <- as.data.frame(cbind(playername, playerid, PAPM))
  remove(playername, playerid, PAPM)
  
  if(i == 1){
    playmaking <- mydf
  } else{
    helper <- mydf
    playmaking <- rbind(playmaking, helper)
  }
  remove(helper, mydf)
  
  i = i + 1
}

colnames(playmaking) <- c("NamePlayer", "idPlayer", "PAPM")
playmaking$NamePlayer <- players$namePlayer
playmaking$PAPM <- as.numeric(levels(playmaking$PAPM))[playmaking$PAPM]
playmaking$idPlayer <- players$idPlayer
playmaking[is.na(playmaking)] <- 0

```

# Using pbp data to obtain relevant dataframe:
```{r}
seasons <- c("2018-19", "2017-18", "2016-17", "2015-16", "2014-15", "2013-14")

for(i in 1:length(seasons)){
  myseason <- read.csv(paste("/Users/patricksimpson/Desktop/Test/pbpdata ", seasons[i], ".csv", sep = ""))
  cleaning <- myseason %>% select(EntityId, Name, GamesPlayed, Assists, X2ptAssists, AtRimAssists,X3ptAssists, Arc3Assists, Corner3Assists, OffPoss, Turnovers, LiveBallTurnovers, DeadBallTurnovers)
  cleaning <- mutate(cleaning, slugSeason = seasons[i])
  
  if(i == 1){
    master <- cleaning
  } else{
    helper <- cleaning
    master <- rbind(master, helper)
  }
  i = i + 1
}
remove(seasons, myseason, helper, cleaning)

master <- master %>% select(slugSeason, EntityId:DeadBallTurnovers)
```

# Getting Passes made and potential assists for every player
```{r}
for(i in 1:nrow(master)){
  seasonlookup <- master[i,1]
  idlookup <- master[i,2]
  passingdf <- Passing %>% filter(SEASON == seasonlookup & idPlayer == idlookup)
  newplayerdf <- cbind(passingdf[1,9], passingdf[1,13])
  
  if(i == 1){
    mydf <- newplayerdf
  } else{
    helper <- newplayerdf
    mydf <- rbind(mydf, helper)
  }
  i = i + 1
}

remove(seasonlookup, idlookup, passingdf, newplayerdf, helper)
```

# Adding df to each other
```{r}
master <- cbind(master, mydf)
remove(mydf)
```


```{r}
master <- master %>% mutate(pa_to_pass = POTENTIAL_AST / PASSES_MADE)



```



```{r}
# Conventional Wisdom: most valuable shots are at the rim and corner 3s... players who can create a lot of these shots are "good" playmakers

# write.csv(master, "/Users/patricksimpson/Desktop/Test/master.csv", row.names = FALSE)



master <- master %>% mutate(component = (AtRimAssists / Assists) * restrictedpercentage(season = slugSeason) * 2 +
                              (Corner3Assists / Assists) * corner3percentage(season = slugSeason) * 3 +
                              (Arc3Assists / Assists) * atb3percentage(season = slugSeason) * 3 +
                              ((Assists - X3ptAssists - AtRimAssists) / Assists) * midrangepercentage(season = slugSeason)*2 -
                              (LiveBallTurnovers / Turnovers) * 1.194 -
                              (DeadBallTurnovers / Turnovers) * .986 + pa_to_pass + 
                              ifelse(Assists > GamesPlayed*2, 1, 0))

master1 <- master %>% filter(GamesPlayed > 30 & OffPoss > 200) %>% mutate(zscore = scale(component))



```
