---
title: "Visuals"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jpeg)
library(png)
library(grid)
library(ggplot2)
```

# Harden 18-19
```{r}
library(grid)
library(jpeg)


# plot using NBA court background and colour by shot zone
ggplot(harden, aes(x=locationX, y=locationY)) + 
      annotation_custom(court, -250, 250, -50, 420) +
      geom_point(aes(colour = zoneBasic)) +
      xlim(-250, 250) +
      ylim(-50, 420)

img2 <- readJPEG("/Users/patricksimpson/Desktop/nba_court.jpg")
court <- rasterGrob(img, width = unit(1,"npc"), height = unit(1,"npc"))
court2 <- rasterGrob(img2, width = unit(1,"npc"), height = unit(1,"npc"))

pic <- readPNG("/Users/patricksimpson/Desktop/201935.png", native = FALSE)
pic1 <- rasterGrob(pic, width = unit(1,"npc"), height = unit(1,"npc"))

ggplot(harden, aes(x=locationX, y=locationY)) + annotation_custom(court2, -250, 250, -52, 420) + annotation_custom(pic1, 148, 248, 325, 425) +geom_point(aes(colour = typeEvent, alpha = 0.3)) + scale_color_manual(values = c("#009E73", "#FF0000"))

```

# Gerald Green 16-17
```{r}
library(jpeg)
library(png)
library(grid)
library(ggplot2)

gerald <- shootingdata %>% filter(namePlayer == "Gerald Green" & slugSeason == "2017-18")

img <- readJPEG("/Users/patricksimpson/Desktop/NBAHC/Visuals/nba_court.jpg")
court <- rasterGrob(img, width = unit(1,"npc"), height = unit(1,"npc"))



ggplot(data, aes(x=V1, y=V2)) + annotation_custom(court, -250, 250, -52, 420) + xlim(-228,228) + ylim(-32, 402) + annotate("rect", xmin = -225, xmax = 225, ymin = -50, ymax = 50, alpha = .5) + xlab("") + ylab("") + theme(axis.text.x = element_blank(), axis.text.y = element_blank(), axis.ticks = element_blank()) + annotate("text", x = 0, y = 70, label = "Paint - Non RA", fontface = 2, size = 5) + annotate("text", x = 0, y = 300, label = "Above the Break Three", fontface = 2, size = 7) + annotate("text", x = 135, y = 70, label = "Mid-Range", fontface = 2, size = 7) + annotate("text", x = -135, y = 70, label = "Mid-Range", fontface = 2, size = 7) + annotate("text", x = -225, y = 20, label = "Corner 3", fontface = 2, size = 7, angle = 90) + annotate("text", x = 225, y = 20, label = "Corner 3", fontface = 2, size = 7, angle = 270) + annotate("text", x = 0, y = 20, label = "Restricted Area", fontface = 2, size = 3)


```


```{r}

lastyear <- shootingdata %>% filter(slugSeason == "2018-19")
ggplot(lastyear, aes(x=locationX, y=locationY)) + annotation_custom(court2, -250, 250, -52, 420) + geom_point(aes(colour = typeEvent, alpha = 0.5)) + scale_color_manual(values = c("#009E73", "#FF0000"))

```
