---
title: "Shotcreating"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
season = "2018-19"
# Getting rosters for given season
players <- rosters %>% filter(slugSeason == season)
players$namePlayer <- as.character(players$namePlayer)
players$idPlayer <- as.integer(players$idPlayer)


for (i in 1:nrow(players)){
  playername <- players[i,5] # Player Name
  playerid <- players[i,14] # Player ID
  
  zeroatt <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "0 Dribbles") %>% summarise(count = sum(fga))) # attempts off 0 dribbles
  
  zeromakes <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "0 Dribbles") %>% summarise(count = sum(fgm))) # makes off 0 dribbles
  
  oneatt <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "1 Dribble") %>% summarise(count = sum(fga))) # attempts off 1 dribble

  onemakes <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "1 Dribble") %>% summarise(count = sum(fgm))) # makes off 1 dribble

  twoatt <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "2 Dribbles") %>% summarise(count = sum(fga))) # attempts off 2 dribbles

  twomakes <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "2 Dribbles") %>% summarise(count = sum(fgm))) # makes off 2 dribbles

  threeatt <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "3-6 Dribbles") %>% summarise(count = sum(fga))) # attempts off 3-6 dribbles

  threemakes <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "3-6 Dribbles") %>% summarise(count = sum(fgm))) # makes off 3-6 dribbles

  sevenatt <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "7+ Dribbles") %>% summarise(count = sum(fga))) # attempts off 7+ dribbles

  sevenmakes <- as.integer(dribdefense %>% filter(idPlayer == as.integer(playerid)) %>% filter(Season == season) %>% filter(rangeDribble == "7+ Dribbles") %>% summarise(count = sum(fgm))) # makes off 7+ dribbles

  playerdf <- as.data.frame(cbind(season, playername, playerid, zeroatt, zeromakes, oneatt, onemakes, twoatt, twomakes, threeatt, threemakes, sevenatt, sevenmakes))
  
  if(i == 1){
    shotcreating <- playerdf
  } else{
    helper <- playerdf
    shotcreating <- rbind(shotcreating, helper)
  }
  
  i = i + 1
  
}
# Removing unnessary variables from environment:
remove(zeroatt, zeromakes, oneatt, onemakes, twoatt, twomakes, threeatt, threemakes, sevenatt, sevenmakes, helper, playerdf)

# Changing factors columns to integer columns:
shotcreating$season <- as.character(shotcreating$season)
shotcreating$playername <- as.character(shotcreating$playername)
shotcreating$playerid <- as.integer(as.character(shotcreating$playerid))
shotcreating$zeroatt <- as.integer(as.character(shotcreating$zeroatt))
shotcreating$zeromakes <- as.integer(as.character(shotcreating$zeromakes))
shotcreating$oneatt <- as.integer(as.character(shotcreating$oneatt))
shotcreating$onemakes <- as.integer(as.character(shotcreating$onemakes))
shotcreating$twoatt <- as.integer(as.character(shotcreating$twoatt))
shotcreating$twomakes <- as.integer(as.character(shotcreating$twomakes))
shotcreating$threeatt <- as.integer(as.character(shotcreating$threeatt))
shotcreating$threemakes <- as.integer(as.character(shotcreating$threemakes))
shotcreating$sevenatt <- as.integer(as.character(shotcreating$sevenatt))
shotcreating$sevenmakes <- as.integer(as.character(shotcreating$sevenmakes))

# Obtaining shot attempts:
shotcreating <- shotcreating %>% mutate(fga = zeroatt + oneatt + twoatt + threeatt + sevenatt) %>% select(season:playerid, fga, zeroatt:sevenmakes)

# Changing makes columns into field goal percentages:
shotcreating <- shotcreating %>% mutate(zeromakes = ifelse(zeroatt != 0, zeromakes / zeroatt, 0)) %>% mutate(onemakes = ifelse(oneatt != 0, onemakes / oneatt, 0)) %>% mutate(twomakes = ifelse(twoatt != 0, twomakes / twoatt, 0)) %>% mutate(threemakes = ifelse(threeatt != 0, threemakes / threeatt, 0)) %>% mutate(sevenmakes = ifelse(sevenatt != 0, sevenmakes / sevenatt, 0))

# Changing attempts columns into proportion of field goal attempts:
shotcreating <- shotcreating %>% mutate(zeroatt = ifelse(fga != 0, zeroatt / fga, 0)) %>% mutate(oneatt = ifelse(fga != 0, oneatt / fga, 0)) %>% mutate(twoatt = ifelse(fga != 0, twoatt / fga, 0)) %>% mutate(threeatt = ifelse(fga != 0, threeatt / fga, 0)) %>% mutate(sevenatt = ifelse(fga != 0, sevenatt / fga, 0))


# Obtaining average fgp based on # of dribbles during given season:

zerodrib <- as.numeric(dribdefense %>% filter(Season == season) %>% filter(rangeDribble == "0 Dribbles") %>% summarise(fgp = sum(fgm) / sum(fga))) # average fgp off 0 dribbles during season

onedrib <- as.numeric(dribdefense %>% filter(Season == season) %>% filter(rangeDribble == "1 Dribble") %>% summarise(fgp = sum(fgm) / sum(fga))) # average fgp off 1 dribble during season

twodrib <- as.numeric(dribdefense %>% filter(Season == season) %>% filter(rangeDribble == "2 Dribbles") %>% summarise(fgp = sum(fgm) / sum(fga))) # average fgp off 2 dribbles during season

threedrib <- as.numeric(dribdefense %>% filter(Season == season) %>% filter(rangeDribble == "3-6 Dribbles") %>% summarise(fgp = sum(fgm) / sum(fga))) # average fgp off 3-6 dribbles during season

sevendrib <- as.numeric(dribdefense %>% filter(Season == season) %>% filter(rangeDribble == "7+ Dribbles") %>% summarise(fgp = sum(fgm) / sum(fga))) # average fgp off 7+ dribbles during season

# Calculating fgp above average:
shotcreating <- shotcreating %>% mutate(fgpae = fga * 0.005 * sevenatt * sevenmakes) %>% mutate(gb = fga * 0.005 * sevenatt * (sevenmakes - sevendrib)) %>% mutate(total = fgpae + gb)



```







