#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 21 22:34:55 2020

@author: patricksimpson
"""

import bs4 as bs
import urllib.request
import pandas as pd

sauce = urllib.request.urlopen('https://fivethirtyeight.com/features/introducing-raptor-our-new-metric-for-the-modern-nba/')
soup = bs.BeautifulSoup(sauce, 'lxml')
table = soup.find('table')

table_rows = table.find_all('tr')

#for tr in table_rows:
 #   td = tr.find_all('td')
  #  row = [i.text for i in td]
   # print(row)
   
   
dfs = pd.read_html('https://fivethirtyeight.com/features/introducing-raptor-our-new-metric-for-the-modern-nba/')
for df in dfs:
    print(df.head())